### ISSUE TITLE
ax6's to-do list

### ISSUE THREAD

**Issue by aaaaaa123456789** [TwitchPlaysPokemon/chattycrystal#1]
Add stuff here as needed.

- [x] Implement box switching on save
- [x] Shift intro Chatot image up by a few pixels
- [x] Port better RNG to ensure bad RNG safeguards can be removed safely
- [X] Add a few extra PC boxes if possible
- [x] Randomize cursor position for new names
- [x] Fix move names in selection menus when alternate names are in use
- [x] Expand mon animations to use 255 tiles (looks like I did this for pokecrystal16 already)
- [x] Display National Dex numbers in the HoF screen
- [x] Ensure `data/pokemon/first_stages.asm` is updated
- [x] Attempt to handle forms somehow (Burmy, Wormadam, Shellos, Gastrodon)
- [x] Ensure Eevee's evolutions don't break the game (looks like I did this for pokecrystal16 already)
- [x] Add Lightning Sapphire names for gen 3 moves and VC+LS name for chatty Hidden Power
- [x] Fix Kris's palette
- [x] Don't display trainer class names when they're empty
- [x] ~~Check move allocation (ensure all moves are used)~~ (deferred to prerelease)
- [x] Hide the New Game option when a save exists (TPP mode)
- [x] Ensure that movelearns during battles with alternate move names don't use the alternate names
- [x] Make chatty moves block disposal of the Pokémon and/or the move (cannot be daycared or released, cannot be deposited, cannot be overwritten or deleted)
- [x] Expand the move animation engine to take effects from multiple banks
- [x] Make all TMs repeatably obtainable in the postgame
- [x] ~~Remove all placeholders~~ (deferred to post-run since some things are not done)
- [x] Reset legendary and one-off Pokémon (and related items like Up-Grade) after E4 clearing
- [x] Fix the visual glitches on the dex printer
